spring:
  profiles:
    active: dev
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
      logging:
        level:
          org:
            hibernate:
              SQL: debug
    platform: org.hibernate.dialect.MySQL5Dialect
  application:
    name: Veterinary Clinic Backend Service
  datasource:
    url: jdbc:mysql://localhost:3306/veterinary
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver


cookie:
  same-site: Lax
  secure: false
